version: '3'
services:
  smokeping:
    #image: linuxserver/smokeping:57c0ea26-ls99
    image: linuxserver/smokeping:latest
    container_name: smokeping
    hostname: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    restart: unless-stopped
    volumes:
        - ./data/smokeping/config:/config
        - ./data/smokeping/data:/data
    ports:
      - 8080:80

  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    restart: always
    network_mode: "host"
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb
      - ./data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./data/influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME} # sourced from .env
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env

  telegraf:
    image: telegraf:latest
    restart: always
    container_name: telegraf
    network_mode: "host"
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
        #- HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      - ./data/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        #- /sys/class/thermal/thermal_zone0/temp:/sys/class/thermal/thermal_zone0/temp:ro
      - /:/hostfs:ro

  grafana:
    container_name: grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
    hostname: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      # to be modified depending on your needs
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
