version: '3'
services:
  #  smokeping:
  #    #image: linuxserver/smokeping:57c0ea26-ls99
  #    image: linuxserver/smokeping:latest
  #    container_name: smokeping
  #    hostname: smokeping
  #    environment:
  #      - PUID=1000
  #      - PGID=1000
  #      - TZ=Europe/Berlin
  #    restart: unless-stopped
  #    volumes:
  #      - ./data/smokeping/config:/config
  #      - ./data/smokeping/data:/data
  #    ports:
  #      - 8080:80

  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    restart: always
    network_mode: "host"
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb
      - ./data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./data/influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME} # sourced from .env
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env

  telegraf:
    build:
      context: ./containers/telegraf
    image: telegraf:raspi-stack
    restart: always
    container_name: telegraf
    network_mode: "host"
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
      - COMMUNITY_STRING=${COMMUNITY_STRING}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_NAME=${INFLUXDB_NAME}
      - INFLUXDB_URL=${INFLUXDB_URL}
    volumes:
      - ./data/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro

  grafana:
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=http://${IP_ADDRESS}:3000
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ALERTING_ENABLED=true
      - GF_RENDERING_SERVER_URL=http://${IP_ADDRESS}:8081/render
      - GF_RENDERING_CALLBACK_URL=http://${IP_ADDRESS}:3000
    hostname: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      # to be modified depending on your needs
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning

  grafana-renderer:
    container_name: grafana-renderer
    image: hferreira/grafana-image-renderer:latest
    hostname: grafana-renderer
    network_mode: "host" 
    restart: unless-stopped
     
  unifi-poller:
    restart: always
    image: golift/unifi-poller:${POLLER_TAG}
    network_mode: "host"
    environment:
      - UP_INFLUXDB_DB=${INFLUXDB_NAME}
      - UP_INFLUXDB_USER=${INFLUXDB_USERNAME}
      - UP_INFLUXDB_PASS=${INFLUXDB_PASSWORD}
      - UP_INFLUXDB_URL=${INFLUXDB_URL}
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
      - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}
      - UP_POLLER_DEBUG=${POLLER_DEBUG}
      - UP_UNIFI_DEFAULT_SAVE_DPI=${POLLER_SAVE_DPI}

        #iobroker:
    #container_name: iobroker
      #image: buanet/iobroker
      #hostname: iobroker
      #volumes:
      #- ./data/iobroker:/opt/iobroker
        #restart: always
      #ports:
      #      - "8082:8081"
      #
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    network_mode: "host"
    volumes:
      - ./data/mosquitto/passwd:/mosquitto/passwd
      - ./data/mosquitto/config:/mosquitto/config
    restart: unless-stopped

