version: '3.9'
services:

######################################### Immich #########################################

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /homiepool/backups/Fotoarchiv:/mnt/media/Fotoarchiv:ro
    ports:
      - "2283:3001"
      - "9230:9230"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
      #mem_limit: "512m"
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /homiepool/backups/Fotoarchiv:/mnt/media/Fotoarchiv:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
      #mem_limit: "4g"
    ports:
      - "3013:3003"
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ./data/immich/model-cache:/cache
      - /homiepool/backups/Fotoarchiv:/mnt/media/Fotoarchiv:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: unless-stopped
    ports:
      - "5432:5432"
