version: '3'
services:
  controller:
    hostname: controller
    image: lscr.io/linuxserver/unifi-controller 
    container_name: ${PROJECT_NAME}_controller
    restart: unless-stopped 
    env_file:
      - ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - ./data/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional

  pihole:
    image: pihole/pihole:latest
    container_name: ${PROJECT_NAME}_pihole
    hostname: pihole
    restart: unless-stopped
    network_mode: host
    cap_add:
        - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: ${TZ}
      ServerIP: ${IP_ADDRESS}
      PIHOLE_DNS_: ${PIHOLE_DNS}
      DNSMASQ_LISTENING: all
      WEBPASSWORD: ${PROJECT_PW}
    volumes:
      - './data/pihole/pihole/:/etc/pihole/'
      - './data/pihole/dnsmasq.d/:/etc/dnsmasq.d/'

