version: '3.4'
services:
  controller:
    hostname: controller
    image: ryansch/unifi-rpi:6.5
    container_name: ${COMPOSE_PROJECT_NAME}_controller
    restart: always
    # Uncomment the following to set java options
    # environment:
    #   JAVA_OPTS: -Xmx512M
    volumes:
      # Unifi v5.0.7 creates all of these directories (some remain empty)
      - ./data/unifi/config:/var/lib/unifi
      - ./data/unifi/log:/usr/lib/unifi/logs
      - ./data/unifi/log2:/var/log/unifi
      - ./data/unifi/run:/usr/lib/unifi/run
      - ./data/unifi/run2:/run/unifi
      - ./data/unifi/work:/usr/lib/unifi/work
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    networks:
      - overlaynet

  nginx:
    hostname: nginx
    image: nginx:1.21.4
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: always
    ports:
      # Public HTTP Port:
      #- '80:80'
      # Public HTTPS Port:
      - '443:443'
    volumes:
      - ./containers/nginx/:/etc/nginx/conf.d
      - ./data/ssl/:/ssl
    networks:
      - overlaynet

networks:
  overlaynet:
    driver: bridge  
